server.port: 8080
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

spring:
  application:
    name: gateway-service
  cloud:
    kubernetes:
      loadbalancer:
        mode: SERVICE
    gateway:
      routes:
      - id: api-service
        uri: ${API_SERVICE_ROUTE:http://localhost:8097}
        predicates:
        - Path=/api/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}